language: csharp

mono: 5.2.0
dotnet: 2.0.0

install:
  - mozroots --import --sync
  # workaround for missing .net 4.5 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 2.0.0
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dotnet: 2.0.0
      dist: trusty
      sudo: required

script: 
  - dotnet --info
  - dotnet restore
  - dotnet build -c Release
  - dotnet test --no-build -c Release tests\Chiron.Tests\Chiron.Tests.fsproj
  - dotnet pack --no-build -c Release src/Chiron
  #- dotnet benchmarks\Chiron.Benchmarks\bin\Release\netcoreapp2.0\Chiron.Benchmarks.dll --class SwaggerSchema

branches:
  except:
    - gh-pages
